// Filter actions
export const FILTER = 'FILTER';

// Exchange actions
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const RECEIVED_PRODUCTS = 'RECEIVED_PRODUCTS';
export const FAILED_FETCH_PRODUCTS = 'FAILED_FETCH_PRODUCTS';

export const FETCHING_PRODUCT_PRICES = 'FETCHING_PRODUCT_PRICES';
export const RECEIVED_PRODUCT_PRICES = 'RECEIVED_PRODUCT_PRICES';
export const FAILED_FETCH_PRODUCT_PRICES = 'FAILED_FETCH_PRODUCT_PRICES';
